# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

{{- if ne (.Values.prometheusRules.ruleGroups.netappMediatorAlerts | toString) "false" }}
groups:
  - name: mediator_suspended_alert_final
    interval: 1m
    rules:
      - record: mediator_suspended_alert_trigger
        expr: |
          max by (netapp_cluster, node, datacenter, cluster_uuid, ipAddress) (
            max_over_time(ems_events{message="sm.mediator.suspended"}[2m])
          )
      - record: mediator_suspended_ok_trigger
        expr: |
          max by (netapp_cluster, node, datacenter, cluster_uuid, ipAddress) (
            max_over_time(ems_events{message="sm.mediator.resumed"}[2m])
          )
      - record: mediator_suspended_alert_persistent
        expr: |
          (
            mediator_suspended_alert_trigger
            or
            mediator_suspended_alert_persistent
          )
          unless
          mediator_suspended_ok_trigger

  - name: mediator_suspended_alerts
    rules:
      - alert: MediatorSuspended
        expr: mediator_suspended_alert_persistent == 1
        for: 2m
        labels:
          severity: warning
          support_group: {{ dig "support_group" "storage" (.Values.prometheusRules.commonLabels | default dict) }}
          team: {{ dig "team" "sci-storage-ops" (.Values.prometheusRules.commonLabels | default dict) }}
          component: netapp_mediator
        annotations:
          summary: '🟡 ONTAP Mediator was suspended on cluster {{ "{{ $labels.netapp_cluster }}" }} having mediator IP address {{ "{{ $labels.ipAddress }}" }}.'
          description: |
            'ONTAP Mediator was suspended on cluster {{ "{{ $labels.netapp_cluster }}" }} having mediator IP address {{ "{{ $labels.ipAddress }}" }}.
            This message will resolve automatically when the Mediator will be successfully resumed.
            Cluster: {{ "{{ $labels.netapp_cluster }}" }}, Node: {{ "{{ $labels.node }}" }} 
            Datacenter: {{ "{{ $labels.datacenter }}" }}, LOB: {{ "{{ $labels.lob }}" }},  Service: {{ "{{ $labels.Service }}" }}'
 {{- else }}
 groups: []
 {{- end }}
 