groups:
  - name: nvmem_battery_capacity_low_final
    interval: 1m
    rules:
      - record: nvmem_battery_capacity_low_trigger
        expr: |
          max by (netapp_cluster, node, datacenter, cluster_uuid, name) (
            max_over_time(ems_events{message="nvmem.battery.capacity.low"}[2m])
          )
      - record: nvmem_battery_capacity_normal_trigger
        expr: |
          max by (netapp_cluster, node, datacenter, cluster_uuid, name) (
            max_over_time(ems_events{message="nvmem.battery.capacity.normal"}[2m])
          )
      - record: nvmem_battery_capacity_low_persistent
        expr: |
          (
            nvmem_battery_capacity_low_trigger
            or
            nvmem_battery_capacity_low_persistent
          )
          unless
          nvmem_battery_capacity_normal_trigger

  - name: nvmem_battery_capacity_low_alerts
    rules:
      - alert: NvmemBatteryCapacityLow
        expr: nvmem_battery_capacity_low_persistent == 1
        for: 2m
        labels:
          severity: warning
          support_group: storage
          team: sci-storage
          component: netapp_nvdimm
        annotations:
          summary: '🟡 NVMEM Battery Capacity Low on {{ "{{ $labels.name }}" }}'
          description: |
            'The NVMEM battery capacity is low on node {{ "{{ $labels.name }}" }} (Cluster: {{ "{{ $labels.netapp_cluster }}" }}). 
            The alert resolves when the event "nvmem.battery.capacity.normal" is detected.
            Cluster: {{ "{{ $labels.netapp_cluster }}" }}, Node: {{ "{{ $labels.node }}" }} 
            Datacenter: {{ "{{ $labels.datacenter }}" }}, LOB: {{ "{{ $labels.lob }}" }},  Service: {{ "{{ $labels.Service }}" }}'

  - name: nvram_battery_capacity_low_warn_final
    interval: 1m
    rules:
      - record: nvram_battery_capacity_low_warn_trigger
        expr: |
          max by (netapp_cluster, node, datacenter, cluster_uuid, name) (
            max_over_time(ems_events{message="nvram.battery.capacity.low.warn"}[2m])
          )
      - record: nvram_battery_capacity_normal_trigger
        expr: |
          max by (netapp_cluster, node, datacenter, cluster_uuid, name) (
            max_over_time(ems_events{message="nvram.battery.capacity.normal"}[2m])
          )
      - record: nvram_battery_capacity_low_warn_persistent
        expr: |
          (
            nvram_battery_capacity_low_warn_trigger
            or
            nvram_battery_capacity_low_warn_persistent
          )
          unless
          nvram_battery_capacity_normal_trigger

  - name: nvram_battery_capacity_low_warn_alerts
    rules:
      - alert: NvramBatteryCapacityLowWarn
        expr: nvram_battery_capacity_low_warn_persistent == 1
        for: 2m
        labels:
          severity: warning
          support_group: storage
          team: sci-storage
          component: netapp_nvdimm
        annotations:
          summary: '🟡 NVRAM Battery Capacity Low on {{ "{{ $labels.node }}" }}'
          description: |
            'The NVRAM battery capacity is low on node {{ "{{ $labels.node }}" }} (Cluster: {{ "{{ $labels.netapp_cluster }}" }}). 
            The alert resolves when the event "nvram.battery.capacity.normal" is detected.
            Cluster: {{ "{{ $labels.netapp_cluster }}" }}, Node: {{ "{{ $labels.node }}" }} 
            Datacenter: {{ "{{ $labels.datacenter }}" }}, LOB: {{ "{{ $labels.lob }}" }},  Service: {{ "{{ $labels.Service }}" }}'

  - name: nvdimm_ecc_error
    rules:
      - alert: NVdimmECCErrors
        expr: (ems_events{message="callhome.nvdimm.cecc"})
        for: 5m
        labels:
          severity: critical
          support_group: storage
          team: sci-storage
          component: netapp_nvdimm
        annotations:
          summary: '🔴 NVDIMM ECC Error'
          description: |
            'NVDIMM ECC Errors - review cluster logs for further details.
            Cluster: {{ "{{ $labels.netapp_cluster }}" }}, Node: {{ "{{ $labels.node }}" }} 
            Datacenter: {{ "{{ $labels.datacenter }}" }}, LOB: {{ "{{ $labels.lob }}" }},  Service: {{ "{{ $labels.Service }}" }}'
