apiVersion: v2
name: netapp-monitoring-operations
description: Deploys NetApp (and related storage) Prometheus alerting rules as PrometheusRules, plus a PodMonitor that scrapes the NetApp Harvest poller pods.
type: application
version: 1.0.3
appVersion: "1.0.3"
maintainers:
  - name: Ganesh Kugulakrishnan
  - name: Chandrakanth Renduchintala
